name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Dotnet for use with actions
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1.0.0
        with:
          dotnet-version: '3.0.100-preview9-014004' # SDK Version to use.
      - run: dotnet build
