name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Setup Dotnet for use with actions
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - run: dotnet --version
      - run: dotnet build
